const rules= document.querySelector(".rules");
const ruleSection= document.querySelector(".rules-hide");
const cross=document.querySelector(".close-image")
const choice=document.querySelector(".choice");
const step2=document.querySelector(".step-2");
const position2=document.querySelector(".position-2");


// object for mapping
const map={
paper:1,
rock:2,
scissor:3
};
// render the photo generated by computer side
function getScore(userChoosed){
    let n=Math.random();
    n=Math.floor(n*3+1);
    let compSelectedClass;
    let compSelectedClassImageUrl; // this is because i have removed the section 1 which results in we lost all the inner HTML part
    if(n===1){
     compSelectedClass="paper";
     compSelectedClassImageUrl="images/icon-paper.svg";
    }
    else if (n===2){
        compSelectedClass="rock";
        compSelectedClassImageUrl="images/icon-rock.svg";
    }
    else{
        compSelectedClass="scissor";
        compSelectedClassImageUrl="images/icon-scissors.svg"
    }
   // rendering position 2 images
    position2.classList.add(compSelectedClass);
    const image2=position2.querySelector("img");
    image2.setAttribute("src", compSelectedClassImageUrl);


    if (n===userChoosed){
        // draw
       alert("draw");
    }
   else if ((userChoosed===1 && n===2) || (userChoosed===2 && n===3) || (userChoosed===3 && n===1)  )
    {
        //win
       alert("win");
    }
    else{
        //loose
       alert("loose");
    }
    
}





const choiceHandler=function (event) {
const selectedDiv=event.target.closest('div');
choice.remove();
step2.classList.add("visible");
const selectedDivClass=selectedDiv.getAttribute("class");
const selectedDivClassImageURL=selectedDiv.querySelector('img').getAttribute("src");
const image1=step2.querySelector(".position-1");
image1.classList.add(selectedDivClass);
const image1URL=image1.querySelector("img");
image1URL.setAttribute("src",selectedDivClassImageURL );

// for position 2 image for 3 second only
position2.classList.add("pseudo");
setTimeout( ()=>{
position2.classList.remove("pseudo");
},3000);


const n=map[selectedDivClass];
getScore(n);

};



choice.addEventListener('click',choiceHandler);







rules.addEventListener("click",()=>{
    console.log(ruleSection);
ruleSection.classList.toggle("visible");
document.body.classList.toggle("manage-background");

  setTimeout( ()=>{
    ruleSection.classList.remove("visible");  
     document.body.classList.remove("manage-background")
  }, 8000 );
});

cross.addEventListener("click",function(){
    ruleSection.classList.remove("visible");
    document.body.classList.remove("manage-background")

});
