const rules= document.querySelector(".rules");
const ruleSection= document.querySelector(".rules-hide");
const cross=document.querySelector(".close-image")
const choice=document.querySelector(".choice");
const step2=document.querySelector(".step-2");
const position2=step2.querySelector(".position-2");
const result=document.querySelector(".result-box");
const image1=step2.querySelector(".position-1");
// object for mapping
const map={
paper:1,
rock:2,
scissor:3
};

const userSum=[];
const houseSum=[];
// showing result of each turn and saving the data to an array
function showResult(num){
    let text;
    const scoreNo=document.getElementById('score-no');
    const houseNo=document.getElementById('house-no');
    let score=Number(scoreNo.textContent);
    let house=Number(houseNo.textContent);
   

    if (num=== -1){
    text= "You Lose";
    score=score+(-5);
    house=house+10;
    userSum.push(-5);
    houseSum.push(10);
    }
    if (num=== 0){
        text="Draw";
        score=score+3;
        house=house+3;
        userSum.push(3);
    houseSum.push(3);
    }
    if (num=== 1){
        text="You win";
        score=score+10;
        house=house+(-5);
        userSum.push(10);
    houseSum.push(-5);
    }
    

    setTimeout( ()=>{
        result.classList.add("visible");
        result.firstElementChild.textContent=text;
        scoreNo.textContent=score;
        houseNo.textContent=house;
    },3000);
        
  

}












// render the photo generated by computer side
function getScore(userChoosed){
    let n=Math.random();
    n=Math.floor(n*3+1);
    let compSelectedClass;
    let compSelectedClassImageUrl; // this is because i have removed the section 1 which results in we lost all the inner HTML part
    if(n===1){
     compSelectedClass="paper";
     compSelectedClassImageUrl="images/icon-paper.svg";
    }
    else if (n===2){
        compSelectedClass="rock";
        compSelectedClassImageUrl="images/icon-rock.svg";
    }
    else{
        compSelectedClass="scissor";
        compSelectedClassImageUrl="images/icon-scissors.svg"
    }
   // rendering position 2 images
    position2.classList.add(compSelectedClass);
    const image2=position2.querySelector("img");
    image2.setAttribute("src", compSelectedClassImageUrl);


    if (n===userChoosed){
        // draw
       showResult(0);
    }
   else if ((userChoosed===1 && n===2) || (userChoosed===2 && n===3) || (userChoosed===3 && n===1)  )
    {
        //win
      showResult(1);
    }
    else{
        //loose
       showResult(-1);
    }
    
}





const choiceHandler=function (event) {
const selectedDiv=event.target.closest('div');
console.log(selectedDiv);
choice.classList.add("hide");
step2.classList.add("visible");
const selectedDivClass=selectedDiv.getAttribute("class");
console.log(selectedDivClass);
const selectedDivClassImageURL=selectedDiv.querySelector('img').getAttribute("src");

image1.classList.add(selectedDivClass);
const image1URL=image1.querySelector("img");
image1URL.setAttribute("src",selectedDivClassImageURL );

// for position 2 image for 3 second only
position2.classList.add("pseudo");
setTimeout( ()=>{
position2.classList.remove("pseudo");
},3000);


const n=map[selectedDivClass];
getScore(n);

};











rules.addEventListener("click",()=>{
    console.log(ruleSection);
ruleSection.classList.toggle("visible");
document.body.classList.toggle("manage-background");

  setTimeout( ()=>{
    ruleSection.classList.remove("visible");  
     document.body.classList.remove("manage-background")
  }, 8000 );
});

cross.addEventListener("click",function(){
    ruleSection.classList.remove("visible");
    document.body.classList.remove("manage-background")

});

choice.addEventListener('click',choiceHandler); 




const next=document.querySelector(".next-turn");
next.addEventListener("click",()=>{
            // count++;
    
        const selectedDivClass=step2.querySelector(".position-1");
        selectedDivClass.className="position-1";
        console.log(selectedDivClass);
        const selectedDivClass2=step2.querySelector(".position-2");
        selectedDivClass2.className="position-2";
            step2.classList.remove("visible");
            choice.classList.remove("hide");
            result.classList.remove("visible");


            });
           








